apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: maya-ui
spec:
  selector:
    matchLabels:
      app: maya-ui
  template:
    metadata:
      labels:
        app: maya-ui
    spec:
      containers:
      - image: registry.mayadata.io/maya-ui:{{ .Values.server.release }}
        imagePullPolicy: Always
        name: maya-ui
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
      imagePullSecrets:
      - name: {{ .Values.server.dockerSecret }}
